name: dart_event_bus
description: A Dart support keyname and type Event Bus for decoupling applications.
version: 0.0.1
homepage: https://github.com/wittyneko/dart_event_bus
repository: https://github.com/wittyneko/dart_event_bus

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  lint: ^1.2.0
  test: ^1.16.2